### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by 00000000aaaaaaaa** [OwnGoalStudio/NoRedirect#5]
dear developer(s),

it would be nice if there was a toggle to completely disable all app redirects systemwide without having to manually toggle each app individually should one prefer to disable any and all app redirects

**Comment by Lessica** [comment]
We can’t technically make it work. If you simply disable all redirects, you can’t even: open an app from the Home Screen, make a purchase from your wallet app, send a email from your business app, open webpage from your mail app. Too many side effects.
